= Design: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt wesentliche Entwurfsentscheidungen auf Ebene der Komponenten und Module. Diese dienen als Vorgabe für die Implementierung und erleichtern das Systemverständnis.
 
== Ausgewählte Sichten
//Entwurfsklassendiagramme, Sequenzdiagramme
== Models
Die Models sind Klassen, die vom ORM-Mapper benutzt werden. Manche von ihnen werden als Tabelle in der Datenbank gespeichert. Wenn eine Klasse von einer anderen Klasse erbt, werden die geerbten Attribute nicht extra angegeben.

=== Models zu Karteikarten

* *CardBase*: Hält die Basisinformation, die eine Karteikarte halten muss.
** front (String) - Text auf der Vorderseite.
** back (String) - Text auf der Rückseite.

* *Card*: Repräsentiert eine Karte. Diese Klasse ist eine Tabelle. Erbt von *CardBase*.
** id (int): Eindeutige Identifikationsnummer der Karteikarte.
** learning_set (LearningSet): Beziehung zum Lernset, dem die Karteikarte zugehörig ist.

* *CardResponse*: Repräsentiert eine Karte. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu einer Karteikarte angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *CardBase*.
** id (int): Eindeutige Identifikationsnummer der Karteikarte.

=== Models zu Multiple-Choice-Fragen

* *QuestionBase*: Hält die Basisinformation, die eine Multiple-Choice-Frage halten muss.
** question (String): Die Frage, die beantwortet werden soll.

* *Question*: Repräsentiert eine Multiple-Choice-Frage. Diese Klasse ist eine Tabelle. Erbt von *QuestionBase*.
** id (int): Eindeutige Identifikationsnummer der Multiple-Choice-Frage
** answers (list[Answer]): Beziehung zu den Antworten der Multiple-Choice-Frage.
** learning_set (LearningSet): Beziehung zum Lernset, dem die Multiple-Choice-Frage zugehörig ist.

* *QuestionResponse*: Repräsentiert eine Multiple-Choice-Frage. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu einer Multiple-Choice-Frage angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *QuestionBase*.
** id (int): Eindeutige Identifikationsnummer der Multiple-Choice-Frage.
** answers (list[AnswerResponse]): Beziehung zu den Antworten der Multiple-Choice-Frage, hier aber als Response-Klasse.

=== Models zu Antworten von Multiple-Choice-Fragen

* *AnswerBase*: Hält die Basisinformation, die eine Antwort halten muss.
** answer (String): Der Antworttext.
** correct (bool): Information, ob die Antwort die richtige Antwort zu der Frage ist, der sie zugehörig ist.

* *Answer*: Repräsentiert eine Antwort. Diese Klasse ist eine Tabelle. Erbt von *AnswerBase*.
** id (int): Eindeutige Identifikationsnummer der Antwort.
** question_id (int): Eindeutige Identifikationsnummer der Multiple-Choice-Frage, der die Antwort zugehörig ist.
** question (Question): Die Multiple-Choice-Frage, der die Antwort zugehörig ist. 

* *AnswerResponse*: Repräsentiert eine Antwort. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu einer Antwort angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *AnswerBase*.
** id (int): Eindeutige Identifikationsnummer der Antwort. 
** question_id (id): Eindeutige Identifikationsnummer der Multiple-Choice-Frage, der die Anwort zugehörig ist.

=== Models zu Lernsets
* *LearningSetBase*: Hält die Basisinformation, die ein Lernset halten muss.
** name (String): Der Name des Lernsets
** module (String): Der Name des Moduls, für das das Lernset erstellt wurde.

* *LearningSet*: Repräsentiert ein Lernset. Diese Klasse ist eine Tabelle. Erbt von *LearningSetBase*.
** id (int): Eindeutige Identifikationsnummer der Antwort.
** cards (list[Card]): Die Karteikarten des Lernsets.
** questions (list[Question]): Die Multiple-Choice-Fragen des Lernsets.

* *LearningSetResponse*: Repräsentiert ein Lernset. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu einem Lernset angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *LearningSetBase*. 
** id (int): Eindeutige Identifikationsnummer der Antwort.
** cards (list[CardResponse]): Die Karteikarten des Lernsets.
** questions (list[QuestionResponse]): Die Multiple-Choice-Fragen des Lernsets.


== Schnittstellen
Eine detailierte Dokumentation durch FastAPI kann auf dem API Server unter /docs gefunden werden. Sofern die Anfragen erfolgreich abgelaufen sind, ist der HTTP-Statuscode der Antwort 200. Es ist ratsam, jede Antwort darauf zu überprüfen. Die hier folgenden aufgeführten Rückgabewerte der einzelnen Funktionen gelten für den Erfolgsfall.

=== Schnittpunkt für Karteikarten
==== /api/cards/
* *POST*: Erstelle eine Karte.
** *body*: CardBase JSON-Objekt, das die Information der Karte hält.
** *variable* learning_set_id: Die ID des Lernsets, dem die Karteikarte hinzugefügt werden soll.
** *returns*: Card JSON-Objekt, das die Karte beschreibt
* *GET*: Gibt alle Karten zurück.
** *returns*: Liste von CardResponse Objekten.
==== /api/cards/{id}
* *GET*: Gibt die Karte zurück
** *returns*: CardResponse JSON-Objekt der Karte.

==== /api/cards/{id}
* *GET*: Gibt die Karte zurück
** *path variable*: Die ID der gewünschten Karte
** *returns*: Ein CardResponse JSON-Objekt, das die Karte repräsentiert.
* *PUT*: Aktualisiert die Werte eines existierenden Lernsets
** *path variable*: ID des Lernsets, das geändert werden soll
** *returns*: Card Objekt der aktualisierten Karte
* *DELETE*: Löscht die gewünschte Karte
** *returns*: null

=== Schnittpunkt für Multiple Choice Fragen
==== /api/questions/
* *POST*: Erstellt eine Multiple Choice Frage
** *body*: QuestionBase JSON-Objekt, das die Information der Multiple Choice Frage hält.
** *variable* learning_set_id: Die ID des Lernsets, dem die Multiple Choice Frage hinzugefügt werden soll.
** *returns*: Question JSON-Objekt, das die Multiple Choice Frage beschreibt
* *GET*: Gibt alle Multiple Choice Fragen zurück
** *returns*: Liste von QuestionResponse Objekten

==== /api/questions/{id}
* *GET*: Gibt die gewünschte Multiple Choice Frage zurück
* *PUT*: Aktualisiert die gewünschte Multiple Choice Frage
* *DELETE*: Löscht die gewünschte Multiple Choice Frage

==== /api/questions/answers/{id}
* *PUT*: 

=== Schnittpunkt für Lernsets
==== /api/learning_set/
* *POST*: Erstelle ein neues Lernset. Die Funktion nimmt das Objekt, welches das Lernset repräsentiert, entgegen und fügt dieses in die Datenbank hinzu. Bei Erfolg wird das Objekt zurückgegeben.
** *body*: LerningSetBase JSON-Objekt, dass die Informationen zum Lernset hält.
** returns: Card JSON-Objekt
* *GET*: Gibt alle Lernsets zurück. Diese werden als Liste von learning_set Objekten zurückgegeben.
** *optional variable* _module_: Optionaler String, wenn nach Lernsets eines Moduls gefiltert werden soll.
** *returns*: Liste von LearningSet Objekten 

==== /api/learning_set/{learning_set_id}
* *GET*: Gibt ein einzelnes Lernset zurück
** *path variable*: Die ID des Lernsets
** *returns*: LearningSetResponse JSON-Objekt des Lernsets

==== /api/learning_set/{id}
* *DELETE*: Lösche ein Lernset aus der Datenbank. Diese Funktion löscht *ALLE* zugehörigen Fragen und Karteikarten aus der Datenbank.
** *path variable*: Die ID des Lernsets
** *returns*: null
