= Design: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt wesentliche Entwurfsentscheidungen auf Ebene der Komponenten und Module. Diese dienen als Vorgabe für die Implementierung und erleichtern das Systemverständnis.
 
== Ausgewählte Sichten
//Entwurfsklassendiagramme, Sequenzdiagramme

== Datenmodell
Angegeben werden die Models aus _models.py_. Die Models sind Klassen, die vom verwendeten ORM benutzt werden. Manche von ihnen werden als Tabelle in der Datenbank gespeichert. Wenn eine Klasse von einer anderen Klasse erbt, werden die geerbten Attribute nicht extra angegeben.
Zudem werden nur die 

=== Models zu Karteikarten

* *CardBase*: Hält die Basisinformation, um eine Karteikarte zu beschreiben.
** front (String) - Text auf der Vorderseite.
** back (String) - Text auf der Rückseite.

* *Card*: Repräsentiert eine Karte. Diese Klasse wird als Tabelle abgebildet. Erbt von *CardBase*.
** id (int): Eindeutige Identifikationsnummer der Karteikarte.
** learning_set (LearningSet): Beziehung zum Lernset, dem die Karteikarte zugehörig ist.
** learning_set_id (int): ID des Lernsets, dem die Karteikarte zugehörig ist.

* *CardResponse*: Repräsentiert eine Karte. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Karteikarten angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *CardBase*.
** id (int): Eindeutige Identifikationsnummer der Karteikarte.

=== Models zu Multiple-Choice-Fragen

* *QuestionBase*: Hält die Basisinformation, um eine Multiple-Choice-Frage zu beschreiben.
** question (String): Die Frage, die beantwortet werden soll.

* *Question*: Repräsentiert eine Multiple-Choice-Frage. Diese Klasse wird als Tabelle abgebildet. Erbt von *QuestionBase*.
** id (int): Eindeutige Identifikationsnummer der Multiple-Choice-Frage
** answers (list[Answer]): Beziehung zu den Antworten der Multiple-Choice-Frage.
** learning_set (LearningSet): Beziehung zum Lernset, dem die Multiple-Choice-Frage zugehörig ist.
** learning_set_id (id): ID des Lernsets, dem die Multiple-Choice-Frage zugehörig ist.

* *QuestionResponse*: Repräsentiert eine Multiple-Choice-Frage. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Multiple-Choice-Fragen angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *QuestionBase*.
** id (int): Eindeutige Identifikationsnummer der Multiple-Choice-Frage.
** answers (list[AnswerResponse]): Beziehung zu den Antworten der Multiple-Choice-Frage, hier aber als Response-Klasse.

=== Models zu Antworten von Multiple-Choice-Fragen

* *AnswerBase*: Hält die Basisinformation, um eine Antwort zu beschreiben.
** answer (String): Der Antworttext.
** correct (bool): Information, ob die Antwort die richtige Antwort zu der Frage ist, der sie zugehörig ist.

* *Answer*: Repräsentiert eine Antwort. Diese Klasse wird als Tabelle abgebildet. Erbt von *AnswerBase*.
** id (int): Eindeutige Identifikationsnummer der Antwort.
** question_id (int): Eindeutige Identifikationsnummer der Multiple-Choice-Frage, der die Antwort zugehörig ist.
** question (Question): Die Multiple-Choice-Frage, der die Antwort zugehörig ist. 

* *AnswerResponse*: Repräsentiert eine Antwort. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Antworten angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *AnswerBase*.
** id (int): Eindeutige Identifikationsnummer der Antwort. 
** question_id (id): Eindeutige Identifikationsnummer der Multiple-Choice-Frage, der die Anwort zugehörig ist.

=== Models zu Lernsets
* *LearningSetBase*: Hält die Basisinformation, um ein Lernset zu beschreiben.
** name (String): Der Name des Lernsets


* *LearningSet*: Repräsentiert ein Lernset. Diese Klasse wird als Tabelle abgebildet. Erbt von *LearningSetBase*.
** id (int): Eindeutige Identifikationsnummer der Antwort.
** cards (list[Card]): Die Karteikarten des Lernsets.
** questions (list[Question]): Die Multiple-Choice-Fragen des Lernsets.
** module_id (int): ID des Moduls, dem das Lernset zugehörig ist.
** module (Module): Das Modul, dem das Lernset zugehörig ist.

* *LearningSetResponse*: Repräsentiert ein Lernset. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Lernsets angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *LearningSetBase*. 
** id (int): Eindeutige Identifikationsnummer der Antwort.
** cards (list[CardResponse]): Die Karteikarten des Lernsets.
** questions (list[QuestionResponse]): Die Multiple-Choice-Fragen des Lernsets.

=== Models zu Modulen
* *ModuleBase:* Hält die Basisinformationen, um ein Modul zu beschreiben.
** name (String): Der Name des Moduls 
** lecturer (String): Der Name der dozierenden Person
** semester (int): Das Semester, in dem das Modul normalerweise vorgesehen ist. 

* *Module:* Repräsentiert ein Modul. Diese Klasse wird als Tabelle abgebildet. Erbt von *ModuleBase*.
** id (int): Die eindeutige ID des Moduls.
** courses (list[CourseModule]): Verbindung zu den Studiengängen, die ein Modul beinhalten.
** learning_sets (list[LearningSet]): Die Lernsets, die es zu diesem Modul gibt.

* *ModuleResponse:* Repräsentiert ein Modul. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Modulen angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *ModuleBase*.

=== Models zu Nutzern
* *UserBase:* Hält die Basisinformationen, um einen Nutzer zu beschreiben.
** name (String): Der Name des Nutzers.
** faculty (String): Die Fakultät, zu der der Nutzer gehört. 
** curr_semester (int): Das aktuelle Semester, in dem sich der Nutzer befindet.

* *User:* Repräsentiert einen Nutzer. Diese Klasse wird als Tabelle abgebildet. Erbt von *UserBase*.
** id (int): Die eindeutige ID des Nutzers
** course_id (int): Die eindeutige ID des Studiengangs, dem dieser Nutzer zugehörig ist.
** course (Course): Der Studiengang, dem dieser Nutzer zugehörig ist.
** modules (list[ModuleUser]): 
** username (String): Der __einzigartige__ Nutzername des Nutzers
** passwd (bytes): gehashtes und gesaltetes Passwort

* *UserResponse:* Repräsentiert einen Nutzer. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Nutzern angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *UserBase*
** id (int): Die eindeutige ID des Nutzers.
** course_id (int): Die ID des Studiengangs, dem der Nutzer zugehörig ist.


=== Models zu Studiengängen
* *CourseBase:* Hält die Basisinformationen, um ein Studiengang zu beschreiben.
** name (String): Der Name des Studiengangs
** faculty(String): Die Fakultät, der dieser Studiengang zugehörig ist.

* *Course:* Repräsentiert ein Studiengang. Diese Klasse wird als Tabelle abgebildet. Erbt von *CourseBase*.
** id (int): Die eindeutige ID des Studiengangs.
** modules (CourseModule): Verbindung zu den Modulen, die es in einem Studiengang gibt.
** users (User): Verbindung zu den Nutzern, die zu diesem Studiengang gehören.

* *CourseResponse:* Repräsentiert einen Studiengang. Objekte dieser Klasse werden genutzt, wenn inhaltliche Attribute zu Studiengängen angefragt werden und Beziehungsattribute nicht benötigt werden. Erbt von *CourseBase*
** id (int): Die eindeutige ID des Studiengangs.

* *LoginData*: Diese Klasse bündelt die für einen Login relevanten Daten in einer Klasse.
** username (String): Der Nutzername des Nutzers, für den der Loginversuch stattfindet. Verglichen wird mit User.__username__, *nicht* mit User.__name__.
** passwd (String): Das Klartextpasswort, das zum Nutzernamen gehört.

* *CourseModule*: Diese Klasse wird als Tabelle abgebildet und verbindet die Studiengänge mit den Modulen.
** course_id (int): Die ID eines Studiengangs.
** courses (Course): Der zur ID gehörende Studiengang.
** module_id (int): Die ID eines Moduls.
** modules (Module): Das zur ID gehörende Modul.

* *ModuleUser*: Diese Klasse wird als Tabelle abgebildet und verbindet die Module mit den Nutzern. Ein Element aus dieser Tabelle kann über die Kombination von module_id und user_id eindeutig identifiziert werden.
** module_id (int): Die ID eines Moduls.
** module (Module): Das zur ID gehörende Modul.
** user_id (int): Die ID eines Nutzers.
** user (User): Der zur ID gehörende Nutzer.

== Schnittstellen
Eine detailierte Dokumentation durch FastAPI kann auf dem API Server im development mode (siehe /src/backend/README.md) unter /docs gefunden werden. Sofern die Anfragen erfolgreich abgelaufen sind, ist der HTTP-Statuscode der Antwort 200. Es ist ratsam, jede Antwort darauf zu überprüfen. Die hier folgenden aufgeführten Rückgabewerte der einzelnen Funktionen gelten für den Erfolgsfall.

=== Begriffsdefinition
* *body*: benötigter Inhalt im Body der HTTP-Request. Vor allem relevant für *POST* und *PUT* Anfragen.
* *path variable*: Die Pfadvariable, die in jedem Fall mit angegeben werden muss.
** Bsp.: Will man eine Karteikarte der ID 4 löschen, schickt man eine *DELETE* Anfrage an den Endpoint /api/cards/4
* *returns*: Beschreibung des Rückgabewertes der Anfrage. Der Rückgabewert ist im Body der Antwort zu finden.
* *variable*: Variable, die der Anfrage mitgegeben wird. Diese kann optional sein, in diesem Fall wird das mit angegeben.
** Anwendung: Variablen werden ähnlich wie Pfadvariablen mit in den Pfad geschrieben. Sie stehen jedoch am Ende, außerdem sieht ihre Angabe etwas anders aus: "<Path>/?<variable name>=<value>"

=== Schnittpunkt für Karteikarten
==== /api/cards/
* *POST*: Erstelle eine oder mehrere Karten.
** *body*: Liste von CardBase JSON-Objekten, die die Informationen der Karten halten. Diese Liste kann auch nur ein Element enthalten
** *variable* _learning_set_id_: Die ID des Lernsets, dem die Karteikarte hinzugefügt werden soll.
** *returns*: Card JSON-Objekt, das die Karte beschreibt
* *GET*: Gibt alle Karten zurück.
** *optional variable* _learning_set_id_: ID des Lernsets zu dem die Karteikarten gehören sollen. Wird diese Variable nicht angegeben, werden einfach alle existierenden Karteikarten zurückgegeben
** *returns*: Liste von CardResponse JSON-Objekten.

==== /api/cards/{id}
* *GET*: Gibt die Karte zurück
** *path variable*: Die ID der gewünschten Karte
** *returns*: Ein Card JSON-Objekt, das die Karte repräsentiert.
* *PUT*: Aktualisiert die Werte eines existierenden Lernsets
** *path variable*: ID des Lernsets, das geändert werden soll
** *returns*: CardResponse JSON-Objekt der aktualisierten Karte
* *DELETE*: Löscht die gewünschte Karte
** *returns*: null

=== Schnittpunkt für Multiple Choice Fragen
==== /api/questions/
* *POST*: Erstellt eine Multiple Choice Frage
** *body*: QuestionBase JSON-Objekt, das die Information der Multiple Choice Frage hält.
** *variable* learning_set_id: Die ID des Lernsets, dem die Multiple Choice Frage hinzugefügt werden soll.
** *returns*: QuestionResponse JSON-Objekt, das die Multiple Choice Frage beschreibt
* *GET*: Gibt alle Multiple Choice Fragen zurück
** *optional variable* _learning_set_id_: ID des Lernsets zu dem die Multiple Choice Fragen gehören sollen. Wird diese Variable nicht angegeben, werden einfach alle existierenden Multiple Choice Fragen zurückgegeben
** *returns*: Liste von QuestionResponse JSON-Objekten

==== /api/questions/{id}
* *GET*: Gibt die gewünschte Multiple Choice Frage zurück
** *path variable*: Die ID der gewünschten Multiple Choice Frage
** *returns*: QuestionResponse JSON-Objekt der gewünschten Multiple Choice Frage
* *PUT*: Aktualisiert die Fragestellung der gewünschten Multiple Choice Frage
** *body*: QuestionBase JSON-Objekt mit den gewünschten Daten für die Multiple Choice Frage
** *path variable*: ID der zu ändernden Multiple Choie Frage 
** *returns*: QuestionResponse JSON-Objekt der aktualisierten Frage
* *DELETE*: Löscht die gewünschte Multiple Choice Frage
** *path variable*: ID der Multiple Choice Frage, die gelöscht werden soll
** *returns*: null

==== /api/questions/answers/{id}
* *PUT*: Ändert den Text der gewünschten Antwort
** *path variable*: ID der zu ändernden Multiple Choice Frage
** *returns*: AnswerResponse JSON-Objekt der aktualisierten Antwort

=== Schnittpunkt für Lernsets
==== /api/learning_set/
* *POST*: Erstelle ein neues Lernset. Die Funktion nimmt das Objekt, welches das Lernset repräsentiert, entgegen und fügt dieses in die Datenbank hinzu. Bei Erfolg wird das Objekt zurückgegeben.
** *body*: LerningSetBase JSON-Objekt, dass die Informationen zum Lernset hält.
** *returns*: LearningSetResponse JSON-Objekt
* *GET*: Gibt alle Lernsets zurück. Diese werden als Liste von LearningSetResponse JSON-Objekten zurückgegeben.
** *optional variable* _module_: Optionaler String, wenn nach Lernsets eines Moduls gefiltert werden soll.
** *returns*: Liste von LearningSetResponse JSON-Objekten 

==== /api/learning_set/{learning_set_id}
* *GET*: Gibt ein einzelnes Lernset zurück
** *path variable*: Die ID des Lernsets
** *returns*: LearningSetResponse JSON-Objekt des Lernsets

==== /api/learning_set/{id}
* *DELETE*: Lösche ein Lernset aus der Datenbank. Diese Funktion löscht *ALLE* zugehörigen Fragen und Karteikarten aus der Datenbank.
** *path variable*: Die ID des Lernsets
** *returns*: null