= UX-Konzept: HTW-Pruefungsvorbereitung
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die Benutzeroberflächen des Systems {project-system-name} beschrieben. Dies können sein:

* Personas der wichtigsten Stakeholder
* Nutzerkontext
* Wireframes relevanter Benutzeroberflächen
* Zusammenhänge mittels Taskflow-Diagrammen
* Angaben über die Gestaltung der Benutzeroberfläche, z.B. Styling, Bedienbarkeit, ...

== Personas
// Fügen Sie hier als Tabelle oder Bild die Persons der wichtigsten Stakeholder ein
=== Isabell Berger
[%hardbreaks]
*Leitspruch*: „Es ist nicht wichtig lange zu lernen, sondern effizient zu lernen.“
*Demographie*:
*Alter*: 25
*Geschlecht*: weiblich
*Familienstand*: ledig
*Wohnort*: Dresden
*Beruf*: Student der Wirtschaftsinformatik, Werkstudent bei Infineon 

*Verhaltensvariablen*:

introvertiert —————⬤——— extrovertiert

risikoscheu ⬤——————— risikobereit

konservativ ⬤——————— innovativ

Telefon ————⬤———— Chat ———— E-Mail

*Technologische Nutzung*:
Nutzt Computer v. a. beruflich und im Studium (Recherche, Programmieren)
Smartphone nur für Termine und Kommunikation
Aktiv auf Social Media, hohe Sensibilität für Datenschutz
Gute Internetkenntnisse, aber zurückhaltend gegenüber neuen Apps

*Bedürfnisse/Ziele:*
Möchte das Lernen effizienter gestalten. 
Sie ist der Meinung, dass Lernen auch Spaß machen kann, ihrer Meinung nach haben ihr schulische Einrichtungen den Spaß am Lernen genommen.

*Hindernisse/Frustrationen*:
Sie hat Angst, dass der HTW-Prüfungsvorbereiter ihr zu langweilig ist und sie keinen Spaß am Lernen hat.
Legt viel Wert auf Gamification-Elemente.

*Akzeptanzkriterien*:
Der HTW-Prüfungsvorbereiter soll Spaß machen beim Benutzen, man sollte seinen Fortschritt irgendwo visuell wahrnehmen können (Fortschritt=größte Motivation).
Man kann eigene Fragen erstellen und diese beantworten. 

== Nutzungskontext
// Beschreiben Sie die Arbeitsaufgaben, Arbeitsmittel, physische und soziale Umgebung, in der das Produkt genutzt wird. 
// Eventuell sind Angaben zu Fehlerquellen, Häufigkeiten von Ereignisse sowie Bearbeitungsdauern von Vorgängen relevant

//Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.

== Wireframes und Wireflow
// Fügen Sie Wireframes als Bilder oder als Link (z.B. zu einem Miroboard) ein
// Beziehen Sie ihre Wireframes auf konkrete User Stories oder Epics.
