= Architecture Notebook: {project-name}
Frederic_Niklas Egle <s86431@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
:plantumldir: plantuml
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!


== Architekturziele 
//Hinweise: Beschreiben Sie den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).

* Plattformunabhängigkeit: Die Anwendung muss auf unterschiedlichen Geräten (iOS, Android, PC) vollständig funktionsfähig sein

* Wartbarkeit: Die Anwendung muss so aufgebaut sein, dass eine Wartung möglichst einfach ist

* Modularität: Die Anwendung soll in Zukunft mit weiteren Funktionen einfach erweiterbar sein

* Offline-Nutzung: Die Anwendung muss auch ohne Verbindung zum Internet bestimmte Grundfunktionen ermöglichen, damit Nutzer überall lernen können

== Annahmen und Abhängigkeiten
//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

* Das Projekt ist eine Neuentwicklung und hängt nicht von Legacy-Systemen ab
* Das Team hat insgesamt wenig Erfahrung mit Webentwicklung
** Framework mit einfachem Einstieg/flacher Lernkurve
* Anwendung besitzt zunächst geringen Nutzerumfang
** Skalierbarkeit ist vorerst nicht notwendig
* Hosting erfolgt in einer von der HTW bereitgestellten VM

== Architektur-relevante Anforderungen
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.

* Sicherheit
** da sich Nutzer einloggen, muss die Übertragung der Anmeldedaten verschlüsselt sein
** Nutzerdaten, besonders Anmeldedaten wie Passwörter, müssen in sicherer Form gespeichert werden

* Authentifizierung
** unterschiedliche Nutzer sollen nur die eigenen Daten einsehen können

* Fehlertoleranz
** das System soll mit böswilligen Eingaben umgehen können und hierbei nicht abstürzen oder unerwartete Aktionen ausführen

== Entscheidungen, Nebenbedingungen und Begründungen
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

. Vue.JS als Frontend-Framework, da es mehrfach als besonders leicht für den Einstieg in die Webentwicklung empfohlen wurde und zusätzlich selbst Funktionalitäten einer PWA mitbringt
. Kommunikation zwischen Frontend und Backend findet nach den Prinzipien von REST mittels HTTP und JSON statt, da das üblicherweise im Bereich von modernen Webanwendung verwendet wird und somit viele Ressourcen zur Umsetzung zur Verfügung stehen
. FastAPI als Backend-Framework, da nach Auswertung von vergleichbaren Implementationen in FastAPI und Spring, FastAPI als besser lesbar und einfacher eingeschätzt wurde im Gegensatz zu Springs Boilerplate, der bereits für eine Minimalanwendung nötig ist
. SQLModel als ORM, da es eine von FastAPI angepasste Version von SQLAlchemy ist und somit gut in Code mit FastAPI integriert werden kann
. Für das Package Management werden im Frontend npm und im Backend pip verwendet, da es jeweils der Standard der verwendeten Sprache ist
. Als Datenbank wird PostgreSQL genutzt, da es Open-Source, stabil und leistungsfähig ist

== Schichten oder Architektur-Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]

Der zentrale Ansatz der Architektur ist eine für Web-Anwendungen typische Drei-Schichten-Architektur mit Präsentationsschicht (Frontend), Logikschicht (Backend) und Datenhaltungsschicht (Datenbank).
Damit ist das System durch diese Schichten klar strukturiert.

Präsentationsschicht::

Für das Frontend wird die Technologie einer Single-Page-Application (SPA) verwendet.
Um die zu entwickelnde Anwendung ebenfalls offline verwendbar zu machen wird das Konzept einer Progressiv-Web-App (PWA) verwendet, das Caching von relevanten Daten nutzt.
Der Nutzer kann somit nach erstmaligem Aufruf der Webseite diese als Applikation installieren und sie außerhalb des Browsers nutzen.
Das Frontend kommuniziert nach den Prinzipien von REST mit dem Backend.

Logikschicht::

Das Backend wird als RESTful API implementiert.
Diese API antwortet auf die Anfragen des Frontends und gibt die geforderten persistenten Ressourcen zurück bzw. legt diese an.
Das Backend kommuniziert mittels eines Object-Relational Mapping (ORM) mit der Datenbank.
Dieser Ansatz sorgt dafür, dass mithilfe eines Modells der Daten in der gegebenen Programmiersprache einfach mit den Daten interagiert werden kann, da diese wie Objekte der Sprache verwendet werden können.
Zusätzlich spart dies die manuelle Anpassung von SQL-Abfragen bei Anpassung des Datenmodells, was nicht nur aufwendig sondern auch fehleranfällig sein kann, da gegebenenfalls die Anpassung einzelner Stellen vergessen werden können.
Die Verwendung eines ORMs ermöglicht eine feingranulare Ausgabe der Datensätze, so dass nur notwendige, öffentlich relevante Attribute des Datensatzes ausgegeben werden, während schützenswerte, bspw. Datenbank-interne, Attribute verborgen bleiben.
Dies ist besonders dann wichtig, wenn sensible Nutzerdaten, wie bspw. Passwörter, mittels eines Modells gespeichert werden.

Datenhaltungsschicht::

Die Datenhaltungsschicht wird mittels einer SQL Datenbank abgebildet.
Diese wird von dem Backend angesprochen.
Für zusätzliche Einsicht in die Datenbank steht ein Webinterface zur Verfügung.

== Architektursichten (Views)
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

=== Kontextabgrenzung
//Level 1 im C4-Modell
.Kontext Diagramm
[plantuml, "{diagramsdir}/Context", svg]
....
include::{plantumldir}/context.puml[]
....

Das Kontext Diagramm zeigt die Beziehungen zwischen dem zu entwickelnden System und den Nutzergruppen "Studierende" und "Dozierende".

Studierende interagieren mit dem System, um mit Karteikarten oder Multiple-Choice Fragen zu lernen, sich mit anderen Studierenden über Inhalte auszutauschen oder den eigenen Lernstand zu überprüfen.

Dozierende interagieren mit dem System, um Inhalte eigener Module einzustellen, vorhandene Inhalte auf Korrektheit zu prüfen oder sich über Lernstände zu informieren.

Das zu entwickelnde System interagiert nicht mit externen Systemen.

=== Container
//Level 2 im C4-Modell
.Container Diagramm
[plantuml, "{diagramsdir}/Container", svg]
....
include::{plantumldir}/container.puml[]
....

Das Container Diagramm zeigt den internen Aufbau des zu entwickelnden Systems.

Die Nutzenden interagieren mit einer Single-Page Application, welche die nötigen Funktionalitäten für Studierende und Dozierende in deren Browser bereitstellt.

Die Single-Page Application kommuniziert nach den Prinzipien von REST mittels HTTP und JSON mit einer API Application.
Diese API Application stellt Schnittstellen zum Speichern von Daten und Abfragen bereits persistenter Daten zur Verfügung.

Die API Application wiederum kommuniziert mittels eines ORMs mit der Datenbank.
Die Datenbank wird für die persistente Speicherung von Daten wie Karteikarten verwendet.

=== Components
.Component Diagramm Frontend
[plantuml, "{diagramsdir}/Component_Frontend", svg]
....
include::{plantumldir}/components_frontend.puml[]
....

Das Component Diagramm des Frontends zeigt die Komponenten und welche von diesen auf die API Applikation zugreifen.
Hierbei ist sichtbar, dass die Startseite selbst nur als Einstiegspunkt für den Nutzer dient und selbst nicht mit der API Applikation interagiert.
Alle andern Komponenten verfolgen eine bestimmte Funktion, wie beispielsweise das erstellen von Lernsets oder das Lernen mit den Karteikarten.
Diese Komponenten laden jeweils die nötigen Daten aus der API Applikation und stellen diese dann dem Nutzer bereit.

.Component Diagramm Backend
[plantuml, "{diagramsdir}/Component_Backend", svg]
....
include::{plantumldir}/components_backend.puml[]
....

Das Component Diagramm des Backend zeigt die Komponenten und wie diese aufgerufen werden und mit den Datenmodell interagieren.
Alle Komponenten benötigen für ihre Aufgaben bestimmte Datenmodelle, diese werden in der models.py bereitgestellt.
Durch Verwendung eines ORM stellt die models.py ebenfalls die Verbindung zu Datenbank und damit die Persistierung der Daten bereit.

=== Verteilungsdiagramm (Deployment Diagramm)
//Beschreibt die physischen Knoten (Rechner) des Systems und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

.Verteilungsdiagramm
[plantuml, "{diagramsdir}/Deployment", svg]
....
include::{plantumldir}/deploy.puml[]
....

Das Verteilungsdiagramm zeigt wie die Anwendung verteilt ist.
Da die Anwendung mittels Docker Images ausgeliefert wird, läuft das Frontend und Backend getrennt in zwei Docker Containern auf dem Docker Daemon.
Es bietet sich an die Datenbank wie im Diagramm zu sehen auch direkt als Container zu nutzten.
Durch die Container ist es ebenfalls möglich, die Anwendung verteilt zu betreiben.